### ISSUE TITLE
Can't insert empty array to Array(Tuple(...)) column

### ISSUE THREAD

**Issue by citramon** [mymarilyn/clickhouse-driver#177]
Hello! I have a problem with insert.

Versions:
ClickHouse server version 20.11.3.3 (official build)
Python 3.7.9
Collecting clickhouse-driver[lz4]==0.1.5
  Downloading clickhouse_driver-0.1.5-cp37-cp37m-macosx_10_6_intel.whl (281 kB)

My table:
```
create table issue
(
    column1                    LowCardinality(String),
    column2                    LowCardinality(String),
    test1       Array(Tuple(String, UInt32)),
    test2       Array(Tuple(String, UInt32))
)
    engine = ReplacingMergeTree()
        ORDER BY (column1, column2)
        SETTINGS index_granularity = 8192;
```

query:
```
client.execute('INSERT INTO issue (column1, column2, test1, test2) VALUES', [{'column1': 'column1', 'column2': 'column2', 'test1': [('test', 1)], 'test2': []}])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/client.py", line 217, in execute
    columnar=columnar
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/client.py", line 372, in process_insert_query
    types_check=types_check, columnar=columnar)
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/client.py", line 407, in send_data
    self.connection.send_data(block)
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 509, in send_data
    self.block_out.write(block)
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/streams/native.py", line 39, in write
    self.fout, types_check=block.types_check)
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/columns/service.py", line 100, in write_column
    column.write_data(items, buf)
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/columns/arraycolumn.py", line 50, in write_data
    self._write(data, buf)
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/columns/arraycolumn.py", line 113, in _write
    self._write_data(value, buf)
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/columns/arraycolumn.py", line 97, in _write_data
    self.nested_column._write_data(value, buf)
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/columns/arraycolumn.py", line 97, in _write_data
    self.nested_column._write_data(value, buf)
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 81, in _write_data
    self.write_items(prepared, buf)
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/columns/tuplecolumn.py", line 19, in write_items
    return self.write_data(items, buf)
  File "/Users/sbushuev/projects/scream-team/cat-event-collector/env/lib/python3.7/site-packages/clickhouse_driver/columns/tuplecolumn.py", line 16, in write_data
    x.write_data(list(items[i]), buf)
IndexError: list index out of range
```

Insert in clickhouse-console is work:
```
my-clickhouse-server :) INSERT INTO issue (column1, column2, test1, test2) VALUES ('column1', 'column2', [('test', 1)], [])

INSERT INTO issue (column1, column2, test1, test2) VALUES

Query id: 4be70702-e590-4072-95ca-c86cce1ce5ac

Ok.

1 rows in set. Elapsed: 0.003 sec.
my-clickhouse-server :) select * from issue;

SELECT *
FROM issue

Query id: 3fb06b82-3293-4350-b2b2-72db33470250

┌─column1─┬─column2─┬─test1────────┬─test2─┐
│ column1 │ column2 │ [('test',1)] │ []    │
└─────────┴─────────┴──────────────┴───────┘

1 rows in set. Elapsed: 0.002 sec.
```

**Comment by xzkostyan** [comment]
Fix was merged into master.

**Comment by van4oza** [comment]
Still an issue, but now with other error

`[ERROR] TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/var/task/handler.py", line 85, in processor
    result = clickhouse_client.execute(f"""
  File "/var/task/clickhouse_driver/client.py", line 298, in execute
    rv = self.process_insert_query(
  File "/var/task/clickhouse_driver/client.py", line 518, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/var/task/clickhouse_driver/client.py", line 571, in send_data
    self.connection.send_data(block)
  File "/var/task/clickhouse_driver/connection.py", line 587, in send_data
    self.block_out.write(block)
  File "/var/task/clickhouse_driver/streams/native.py", line 38, in write
    write_column(self.context, col_name, col_type, items,
  File "/var/task/clickhouse_driver/columns/service.py", line 157, in write_column
    column.write_data(items, buf)
  File "/var/task/clickhouse_driver/columns/arraycolumn.py", line 44, in write_data
    self._write(data, buf)
  File "/var/task/clickhouse_driver/columns/arraycolumn.py", line 104, in _write
    self._write_sizes(value, buf)
  File "/var/task/clickhouse_driver/columns/arraycolumn.py", line 68, in _write_sizes
    offset += len(x)`

**Comment by sanyapalmero** [comment]
> Still an issue, but now with other error
> 
> ```
> [ERROR] TypeError: object of type 'NoneType' has no len()
> Traceback (most recent call last):
>   File "/var/task/handler.py", line 85, in processor
>     result = clickhouse_client.execute(f"""
>   File "/var/task/clickhouse_driver/client.py", line 298, in execute
>     rv = self.process_insert_query(
>   File "/var/task/clickhouse_driver/client.py", line 518, in process_insert_query
>     rv = self.send_data(sample_block, data,
>   File "/var/task/clickhouse_driver/client.py", line 571, in send_data
>     self.connection.send_data(block)
>   File "/var/task/clickhouse_driver/connection.py", line 587, in send_data
>     self.block_out.write(block)
>   File "/var/task/clickhouse_driver/streams/native.py", line 38, in write
>     write_column(self.context, col_name, col_type, items,
>   File "/var/task/clickhouse_driver/columns/service.py", line 157, in write_column
>     column.write_data(items, buf)
>   File "/var/task/clickhouse_driver/columns/arraycolumn.py", line 44, in write_data
>     self._write(data, buf)
>   File "/var/task/clickhouse_driver/columns/arraycolumn.py", line 104, in _write
>     self._write_sizes(value, buf)
>   File "/var/task/clickhouse_driver/columns/arraycolumn.py", line 68, in _write_sizes
>     offset += len(x)
>     ```
> ```

+1
I have the same error

**Comment by xzkostyan** [comment]
@van4oza @sanyapalmero I'm waiting for minimal reproducible piece of code that will trigger issue.

**Comment by sanyapalmero** [comment]
@xzkostyan I'm using pyspark with clickhouse_driver for writing data from pyspark dataframe to clickhouse database.
Here is code snippet:

```
from clickhouse_driver import Client
from pyspark.sql import SparkSession

"""
CREATE TABLE IF NOT EXISTS test.array_test (
    ids Array(String),
    group Int,
) ENGINE = MergeTree() ORDER BY group
"""

spark = SparkSession.builder.appName("spark-test-array").master("local").getOrCreate()

data = [
    {"ids": [], "group": None},
    {"ids": ["1", "2"], "group": 2},
]
df = spark.createDataFrame(data)
df.show()

def insert_partition_to_clickhouse(partition):
    partition_list = list(partition)
    if not partition_list:
        return []
    
    client = Client(host=CLICKHOUSE_HOST, port=CLICKHOUSE_PORT)
    client.execute(f"INSERT INTO test.array_test (ids, group) VALUES", params=partition_list)
    client.disconnect()
    return partition_list

df.rdd.mapPartitions(insert_partition_to_clickhouse).count()

spark.stop()
```

And after running this code I have the next error: `TypeError: object of type 'NoneType' has no len()`
Full traceback:
```
23/01/17 16:48:59 ERROR Executor: Exception in task 0.0 in stage 9.0 (TID 9)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 686, in main
    process()
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 676, in process
    out_iter = func(split_index, iterator)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 540, in func
    return f(iterator)
  File "/var/folders/q7/dv1741zj08v7rxnytwdq34y00000gq/T/ipykernel_80142/312156337.py", line 26, in insert_partition_to_clickhouse
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 351, in execute
    rv = self.process_insert_query(
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 578, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 631, in send_data
    self.connection.send_data(block)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 604, in send_data
    self.block_out.write(block)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/streams/native.py", line 38, in write
    write_column(self.context, col_name, col_type, items,
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/service.py", line 157, in write_column
    column.write_data(items, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 44, in write_data
    self._write(data, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 104, in _write
    self._write_sizes(value, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 68, in _write_sizes
    offset += len(x)
TypeError: object of type 'NoneType' has no len()
```

**Comment by sanyapalmero** [comment]
@xzkostyan I found some strange behavior:
Updated code:
```
from clickhouse_driver import Client
from pyspark.sql import SparkSession

"""
CREATE TABLE IF NOT EXISTS test.array_test (
    ids Array(String),
    group Nullable(Int),
    id Int
) ENGINE = MergeTree() ORDER BY id
"""

spark = SparkSession.builder.appName("spark-test-array").master("local").getOrCreate()

data = [
    {"ids": [], "group": None, "id": 0},
    {"ids": ["1", "2"], "group": 3, "id": 1},
]
df = spark.createDataFrame(data)
df.show()
df.printSchema()

def insert_partition_to_clickhouse(partition):
    partition_list = list(partition)
    if not partition_list:
        return []
    
    client = Client(host=CLICKHOUSE_HOST, port=CLICKHOUSE_PORT)
    client.execute(f"INSERT INTO test.array_test (ids, group, id) VALUES", params=partition_list)
    client.disconnect()
    return partition_list

df.rdd.mapPartitions(insert_partition_to_clickhouse).count()

spark.stop()
```

I have error:
```
File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 69, in _write_sizes
offset += len(x)
TypeError: object of type 'NoneType' has no len()
```

I tried to print `value` near `offset += len(x)` and I see `[None, 3]` - this is values of `group` column. When we call `df.printSchema()` we can see the next output:
```
root
 |-- group: long (nullable = true)
 |-- id: long (nullable = true)
 |-- ids: array (nullable = true)
 |    |-- element: string (containsNull = true)
```
Here column `group` has `long` type, but clickhouse_driver uses `arraycolumn.py` module for it. Why it happens? I suppose it must be `intcolumn.py` module.

**Comment by xzkostyan** [comment]
@sanyapalmero If you want None to default casting please use `input_format_null_as_default` option.


Following example works for me:

```python
from clickhouse_driver import Client

ddl = """
CREATE TABLE IF NOT EXISTS test.array_test (
    ids Array(String),
    group Int,
) ENGINE = MergeTree() ORDER BY group
"""


data = [
    {"ids": [], "group": None},
    {"ids": ["1", "2"], "group": 2},
]

client = Client('localhost', settings={'input_format_null_as_default': 1})
client.execute(ddl)

client.execute(f"INSERT INTO test.array_test (ids, group) VALUES", data)
```

I suppose something wrong in `partition_list`. Could you print it?

**Comment by sanyapalmero** [comment]
> @sanyapalmero If you want None to default casting please use `input_format_null_as_default` option.
> 
> Following example works for me:
> 
> ```python
> from clickhouse_driver import Client
> 
> ddl = """
> CREATE TABLE IF NOT EXISTS test.array_test (
>     ids Array(String),
>     group Int,
> ) ENGINE = MergeTree() ORDER BY group
> """
> 
> 
> data = [
>     {"ids": [], "group": None},
>     {"ids": ["1", "2"], "group": 2},
> ]
> 
> client = Client('localhost', settings={'input_format_null_as_default': 1})
> client.execute(ddl)
> 
> client.execute(f"INSERT INTO test.array_test (ids, group) VALUES", data)
> ```
> 
> I suppose something wrong in `partition_list`. Could you print it?

Yeah, sure: 
```
partition_list: [Row(group=None, id=0, ids=[]), Row(group=3, id=1, ids=['1', '2'])]
VALUE: [None, 3]

**Comment by sanyapalmero** [comment]
@xzkostyan Unfortunately setting `{'input_format_null_as_default': 1}` cant't help :(
I have the same error.
Full code and full output:

```
from clickhouse_driver import Client
from pyspark.sql import SparkSession

"""
CREATE TABLE IF NOT EXISTS test.array_test (
    ids Array(String),
    group Nullable(Int),
    id Int
) ENGINE = MergeTree() ORDER BY id
"""

spark = SparkSession.builder.appName("spark-test-array").master("local").getOrCreate()

data = [
    {"ids": [], "group": None, "id": 0},
    {"ids": ["1", "2"], "group": 3, "id": 1},
]
df = spark.createDataFrame(data)
df.show()
df.printSchema()

def insert_partition_to_clickhouse(partition):
    partition_list = list(partition)
    print(f"partition_list: {partition_list}")
    if not partition_list:
        return []
    
    client = Client(host=CLICKHOUSE_HOST, port=CLICKHOUSE_PORT, settings={'input_format_null_as_default': 1})
    client.execute(f"INSERT INTO test.array_test (ids, group, id) VALUES", params=partition_list)
    client.disconnect()
    return partition_list

df.rdd.mapPartitions(insert_partition_to_clickhouse).count()

spark.stop()
```

```
+-----+---+------+
|group| id|   ids|
+-----+---+------+
| null|  0|    []|
|    3|  1|[1, 2]|
+-----+---+------+

root
 |-- group: long (nullable = true)
 |-- id: long (nullable = true)
 |-- ids: array (nullable = true)
 |    |-- element: string (containsNull = true)

23/01/17 20:18:07 ERROR Executor: Exception in task 0.0 in stage 23.0 (TID 23)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 686, in main
    process()
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 676, in process
    out_iter = func(split_index, iterator)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 540, in func
    return f(iterator)
  File "/var/folders/q7/dv1741zj08v7rxnytwdq34y00000gq/T/ipykernel_80142/545792750.py", line 29, in insert_partition_to_clickhouse
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 351, in execute
    rv = self.process_insert_query(
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 578, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 631, in send_data
    self.connection.send_data(block)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 604, in send_data
    self.block_out.write(block)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/streams/native.py", line 38, in write
    write_column(self.context, col_name, col_type, items,
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/service.py", line 157, in write_column
    column.write_data(items, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 44, in write_data
    self._write(data, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 105, in _write
    self._write_sizes(value, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 69, in _write_sizes
    offset += len(x)
TypeError: object of type 'int' has no len()

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:559)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:765)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:747)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:512)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1021)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
23/01/17 20:18:07 WARN TaskSetManager: Lost task 0.0 in stage 23.0 (TID 23) (localhost executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 686, in main
    process()
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 676, in process
    out_iter = func(split_index, iterator)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 540, in func
    return f(iterator)
  File "/var/folders/q7/dv1741zj08v7rxnytwdq34y00000gq/T/ipykernel_80142/545792750.py", line 29, in insert_partition_to_clickhouse
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 351, in execute
    rv = self.process_insert_query(
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 578, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 631, in send_data
    self.connection.send_data(block)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 604, in send_data
    self.block_out.write(block)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/streams/native.py", line 38, in write
    write_column(self.context, col_name, col_type, items,
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/service.py", line 157, in write_column
    column.write_data(items, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 44, in write_data
    self._write(data, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 105, in _write
    self._write_sizes(value, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 69, in _write_sizes
    offset += len(x)
TypeError: object of type 'int' has no len()

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:559)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:765)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:747)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:512)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1021)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

23/01/17 20:18:07 ERROR TaskSetManager: Task 0 in stage 23.0 failed 1 times; aborting job
partition_list: [Row(group=None, id=0, ids=[]), Row(group=3, id=1, ids=['1', '2'])]
VALUE: [[], 3]
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Cell In[32], line 33
     30     client.disconnect()
     31     return partition_list
---> 33 df.rdd.mapPartitions(insert_partition_to_clickhouse).count()
     35 spark.stop()

File ~/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py:1521, in RDD.count(self)
   1512 def count(self) -> int:
   1513     """
   1514     Return the number of elements in this RDD.
   1515 
   (...)
   1519     3
   1520     """
-> 1521     return self.mapPartitions(lambda i: [sum(1 for _ in i)]).sum()

File ~/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py:1508, in RDD.sum(self)
   1499 def sum(self: "RDD[NumberOrArray]") -> "NumberOrArray":
   1500     """
   1501     Add up the elements in this RDD.
   1502 
   (...)
   1506     6.0
   1507     """
-> 1508     return self.mapPartitions(lambda x: [sum(x)]).fold(  # type: ignore[return-value]
   1509         0, operator.add
   1510     )

File ~/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py:1336, in RDD.fold(self, zeroValue, op)
   1331     yield acc
   1333 # collecting result of mapPartitions here ensures that the copy of
   1334 # zeroValue provided to each partition is unique from the one provided
   1335 # to the final reduce call
-> 1336 vals = self.mapPartitions(func).collect()
   1337 return reduce(op, vals, zeroValue)

File ~/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py:1197, in RDD.collect(self)
   1195 with SCCallSiteSync(self.context):
   1196     assert self.ctx._jvm is not None
-> 1197     sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
   1198 return list(_load_from_socket(sock_info, self._jrdd_deserializer))

File ~/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/py4j/java_gateway.py:1321, in JavaMember.__call__(self, *args)
   1315 command = proto.CALL_COMMAND_NAME +\
   1316     self.command_header +\
   1317     args_command +\
   1318     proto.END_COMMAND_PART
   1320 answer = self.gateway_client.send_command(command)
-> 1321 return_value = get_return_value(
   1322     answer, self.gateway_client, self.target_id, self.name)
   1324 for temp_arg in temp_args:
   1325     temp_arg._detach()

File ~/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/sql/utils.py:190, in capture_sql_exception.<locals>.deco(*a, **kw)
    188 def deco(*a: Any, **kw: Any) -> Any:
    189     try:
--> 190         return f(*a, **kw)
    191     except Py4JJavaError as e:
    192         converted = convert_exception(e.java_exception)

File ~/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 23.0 failed 1 times, most recent failure: Lost task 0.0 in stage 23.0 (TID 23) (localhost executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 686, in main
    process()
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 676, in process
    out_iter = func(split_index, iterator)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 540, in func
    return f(iterator)
  File "/var/folders/q7/dv1741zj08v7rxnytwdq34y00000gq/T/ipykernel_80142/545792750.py", line 29, in insert_partition_to_clickhouse
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 351, in execute
    rv = self.process_insert_query(
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 578, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 631, in send_data
    self.connection.send_data(block)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 604, in send_data
    self.block_out.write(block)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/streams/native.py", line 38, in write
    write_column(self.context, col_name, col_type, items,
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/service.py", line 157, in write_column
    column.write_data(items, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 44, in write_data
    self._write(data, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 105, in _write
    self._write_sizes(value, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 69, in _write_sizes
    offset += len(x)
TypeError: object of type 'int' has no len()

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:559)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:765)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:747)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:512)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1021)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2672)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2608)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2607)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2607)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1182)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1182)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1182)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2860)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2791)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:952)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2228)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2249)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2268)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2293)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1021)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:406)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1020)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:180)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 686, in main
    process()
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 676, in process
    out_iter = func(split_index, iterator)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 540, in func
    return f(iterator)
  File "/var/folders/q7/dv1741zj08v7rxnytwdq34y00000gq/T/ipykernel_80142/545792750.py", line 29, in insert_partition_to_clickhouse
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 351, in execute
    rv = self.process_insert_query(
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 578, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 631, in send_data
    self.connection.send_data(block)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 604, in send_data
    self.block_out.write(block)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/streams/native.py", line 38, in write
    write_column(self.context, col_name, col_type, items,
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/service.py", line 157, in write_column
    column.write_data(items, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 44, in write_data
    self._write(data, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 105, in _write
    self._write_sizes(value, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/arraycolumn.py", line 69, in _write_sizes
    offset += len(x)
TypeError: object of type 'int' has no len()

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:559)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:765)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:747)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:512)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1021)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	... 1 more
```

**Comment by xzkostyan** [comment]
I don't know what is going on pyspark `Row`, but this works

```python
client.execute(f"INSERT INTO test.array_test (ids, group, id) VALUES", [x.asDict() for x in partition_list])
```

**Comment by sanyapalmero** [comment]
@xzkostyan thank you so much. I get it. Now it works fine!

**Comment by sanyapalmero** [comment]
@xzkostyan Hi, I don't know where I can ask this question, sorry if it's wrong topic, but is it real to insert dataframe with binary column to clickhouse with FixedString(16) type?
My code:

```python
"""
CREATE TABLE IF NOT EXISTS test.binary_test (
    id FixedString(16),
) ENGINE = MergeTree() ORDER BY id
"""

spark = SparkSession.builder.appName("spark-test-binary").master("local").getOrCreate()

df = spark.sql("select unhex('0A54C9E024') as id")

display(df)
df.show()
df.printSchema()

def insert_partition_to_clickhouse(partition):
    partition_list = [x.asDict() for x in list(partition)] 
    print(f"partition_list: {partition_list}")
    if not partition_list:
        return []
    
    client = Client(host=CLICKHOUSE_HOST, port=CLICKHOUSE_PORT)
    client.execute(f"INSERT INTO test.binary_test (id) VALUES", params=partition_list, types_check=True)
    client.disconnect()
    return partition_list

df.rdd.mapPartitions(insert_partition_to_clickhouse).count()

spark.stop()
```

When I print my dataframe and check schema, it looks like this:
```
DataFrame[id: binary]
+----------------+
|              id|
+----------------+
|[0A 54 C9 E0 24]|
+----------------+

root
 |-- id: binary (nullable = true)
```

I just have an error: 
```
Traceback (most recent call last):
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/service.py", line 157, in write_column
    column.write_data(items, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/base.py", line 87, in write_data
    self._write_data(items, buf)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/base.py", line 90, in _write_data
    prepared = self.prepare_items(items)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/base.py", line 71, in prepare_items
    check_item_type(x)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/base.py", line 43, in check_item_type
    raise exceptions.ColumnTypeMismatchException(value)
clickhouse_driver.columns.exceptions.ColumnTypeMismatchException: bytearray(b'\nT\xc9\xe0$')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 686, in main
    process()
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/worker.py", line 676, in process
    out_iter = func(split_index, iterator)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 3472, in pipeline_func
    return func(split, prev_func(split, iterator))
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/pyspark/rdd.py", line 540, in func
    return f(iterator)
  File "/var/folders/q7/dv1741zj08v7rxnytwdq34y00000gq/T/ipykernel_65233/1341876327.py", line 22, in insert_partition_to_clickhouse
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 351, in execute
    rv = self.process_insert_query(
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 578, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/client.py", line 631, in send_data
    self.connection.send_data(block)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/connection.py", line 604, in send_data
    self.block_out.write(block)
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/streams/native.py", line 38, in write
    write_column(self.context, col_name, col_type, items,
  File "/Users/aleksandr.vagner/Work/Projects/clickhouse-spark-jdbc/venv/lib/python3.9/site-packages/clickhouse_driver/columns/service.py", line 160, in write_column
    raise errors.TypeMismatchError(
clickhouse_driver.errors.TypeMismatchError: Code: 53. Type mismatch in VALUES section. Expected FixedString(16) got <class 'bytearray'>: bytearray(b'\nT\xc9\xe0$') for column "id".
```
Maybe I can convert it?
